### ISSUE TITLE
Wistia Plugin adds a lot to page load time.

### ISSUE THREAD

**Issue by zakkleifeste** [wistia/wistia-wordpress-plugin#6]
I did a plugin load time test with the P3 plugin from GoDaddy. According to the test results, the Wistia plugin adds 1.6 seconds to page load time and is the plugin causing the most damage on my site. Is there any fix for that or do I just have to suffer the consequences of having Wistia videos on my site?

Thanks
![screen shot 2013-09-10 at 5 16 34 pm](https://f.cloud.github.com/assets/5131153/1118844/b9c4e3ce-1a66-11e3-948e-404d69ca41be.png)

**Comment by rohanshah2599** [comment]
Hey @MaxPower15, I am not a technical person.

But only what I can see is my homepage takes almost eight secs to load, and that is damaging the seo! 

Can you provide any quick solution to improve the speed?

I am using the Wistia plugin on WordPress.

Check out the site!
[Video Production Melbourne](http://www.lunamik.com.au)

**Comment by jeffvincent** [comment]
Hi @rohanshah2599, thanks for reaching out. The last update on this issue looks to be from 2014, so any updates are probably unrelated to the original issue. My apologies that we left this issue open, but I think we should close it and perhaps a new one should be opened.

Direct to your question - your site is loading great here in the States! I didn't experience the hangup you described. 

I don't believe the plugin (and maybe even Wistia in general) is to blame here. Since 2013-2014, our embeds have become async, so it _should not_ be affecting your page load. That being said, looks like you have many images & videos on the page, so _perhaps_ that is leading to issues? Again, I can't seem to replicate the loading issues you've described so it's hard to say for certain.

We'd be happy to help you at support@wistia.com if you'd like to discuss further, but I'm going to close this issue.
